name: Notify Me Through Telegram
description: Send a Telegram message about a workflow run
inputs:
  telegram_token:
    description: Telegram bot token
    required: true
  telegram_chat_id:
    description: Telegram chat id
    required: true
  message:
    description: Message text (Markdown)
    required: true

runs:
  using: composite
  steps:
    - name: Send Telegram notification
      shell: bash
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
          -d chat_id="${{ inputs.telegram_chat_id }}" \
          -d parse_mode=Markdown \
          -d text="${{ inputs.message }}"




    
